controllerManager:
  # -- (`int`) Number of Oz Controllers to run. If more than one is used,
  # leader-election is used to ensure only one controller is operating at a
  # time.
  replicas: 1

  # -- (`[]map]`) A list of Tolerations that will be applied to the
  # controller-manager pods. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/.
  tolerations: []

  # -- (`map`) A nodeSepector to apply to the controller-manager pods. See
  # https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/.
  nodeSelector:

  manager:
    image:
      # -- (`string`) Docker Image repository and name to use for the controller.
      repository: ghcr.io/diranged/oz

      # -- (`string`) If set, overrides the .Chart.AppVersion field to set the
      # target image version for the Oz controller.
      tag:

    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi

# Configuration for the oz-controller-manager-metrics-service, used for
# collecting metrics from the controller.
metricsService:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https

# -- (`string`) Configures the KUBERNETES_CLUSTER_DOMAIN environment variable.
kubernetesClusterDomain: cluster.local

rbac:
  # -- (`bool`) If true, the chart will create aggregated roles for accessing
  # the access templates and access request resources.
  create: true

  viewAccess:
    # -- (`map`) These labels are applied to the "view-access" ClusterRole and
    # are used to define how to aggregate up the privileges to your RBAC
    # system. The default settings here are reasonably sane.
    aggregateTo:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
      rbac.authorization.k8s.io/aggregate-to-admin: "true"

  templateManager:
    # -- (`map`) These labels are applied to the "template-manager"
    # ClusterRole and are used to define how to aggregate up the privileges
    # for managing Access Templates.
    aggregateTo:
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
      rbac.authorization.k8s.io/aggregate-to-admin: "true"

  requestAccess:
    # -- (`map`) These labels are applied to the "request-access" ClusterRole
    # and are intended to grant developers the permission to make an Access
    # Request. These can be fairly widely granted because the true permissions
    # for who has access to use an Access Request are defined in the Access
    # Template resouces themselves.
    aggregateTo:
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
